services:
  angular-frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - external
      - internal
  backend:
    build:
      context: ./backend
    ports:
      # - "5000:5000" # accessed directly by containers, not exposed publicly
    depends_on:
      - mongo
    networks:
      - internal


networks:
  external:
    driver: bridge
  internal:
    driver: bridge


